{{- if .Values.cart.enabled }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
    component: {{ .Values.cart.name }}
data:
  REDIS_HOST: {{ .Values.cart.config.redisHost | quote }}
  CATALOGUE_HOST: {{ .Values.cart.config.catalogueHost | quote }}
  CATALOGUE_PORT: {{ .Values.cart.config.cataloguePort | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
    component: {{ .Values.cart.name }}
spec:
  replicas: {{ .Values.cart.replicaCount }}
  selector:
    matchLabels:
      {{- include "roboshop.selectorLabels" . | nindent 6 }}
      component: {{ .Values.cart.name }}
  template:
    metadata:
      labels:
        {{- include "roboshop.selectorLabels" . | nindent 8 }}
        component: {{ .Values.cart.name }}
    spec:
        {{- if .Values.cart.serviceAccount.enabled }}
        serviceAccountName: {{ .Values.cart.serviceAccount.name }}
        {{- end }}
      containers:
        - name: {{ .Values.cart.name }}
          image: "{{ .Values.cart.image.repository }}:{{ .Values.cart.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cart.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cart.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.cart.name }}
          {{- if .Values.cart.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.cart.service.targetPort }}
            initialDelaySeconds: {{ .Values.cart.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.cart.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.cart.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.cart.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.cart.probes.liveness.path }}
              port: {{ .Values.cart.service.targetPort }}
            periodSeconds: {{ .Values.cart.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.cart.probes.liveness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.cart.resources | nindent 12 }}
      {{- with .Values.cart.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cart.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cart.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
    component: {{ .Values.cart.name }}
spec:
  type: {{ .Values.cart.service.type }}
  selector:
    {{- include "roboshop.selectorLabels" . | nindent 4 }}
    component: {{ .Values.cart.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.cart.service.port }}
      targetPort: {{ .Values.cart.service.targetPort }}
{{- end }}